// Generated by GitHub Actions — do not edit manually
// For local testing: replace with your Supabase credentials
const APP_CONFIG = {
  SUPABASE_URL: "REPLACE_WITH_YOUR_URL",
  SUPABASE_KEY: "REPLACE_WITH_YOUR_KEY"
};
